import { ProposalTemplate, ProposalTemplateSlide } from '../types/proposal';

const proposalSlides = (titles: Array<[string, ProposalTemplateSlide['contentType'], string]>): ProposalTemplate['slides'] =>
  titles.slice(0, 6).map(([title, contentType, purpose]) => ({ title, contentType, purpose }));

const officeVisualStyle: ProposalTemplate['visualStyle'] = {
  headingFont: 'Aptos Display',
  bodyFont: 'Aptos',
  backgroundColor: 'FFFFFF',
  headingColor: '1F1F1F',
  bodyColor: '44546A',
  accentColors: ['4472C4', 'ED7D31', '70AD47', 'FFC000'],
};

export const PROPOSAL_TEMPLATES: ProposalTemplate[] = [
  {
    id: 'proposal-sharepoint-modernization',
    fileName: 'DTMC_Sample_Proposal_01_SharePoint_Modernization 1.pptx',
    assetPath: '/Asset/proposal-templates/DTMC_Sample_Proposal_01_SharePoint_Modernization 1.pptx',
    name: 'SharePoint Modernization',
    description: 'A transformation story that moves from current-state friction to a governed digital workplace roadmap.',
    audience: 'Executive sponsors and business stakeholders',
    style: 'Clean, outcome-led, and architecture-aware',
    slideCount: 6,
    narrativeFlow: 'Context -> challenges -> solution vision -> architecture -> delivery confidence -> decision',
    visualStyle: officeVisualStyle,
    slides: proposalSlides([
      ['Executive Overview', 'cover', 'Frame the engagement and the business outcome.'],
      ['Current State and Challenges', 'narrative', 'Make the client pain concrete and specific.'],
      ['Modernization Opportunity', 'narrative', 'Connect needs to a compelling future state.'],
      ['Proposed Solution', 'narrative', 'Explain the recommended capabilities and value.'],
      ['Solution Architecture', 'architecture', 'Show the target-state design principles.'],
      ['Experience and Governance Model', 'narrative', 'Describe adoption, controls, and operating rhythm.'],
      ['Delivery Roadmap', 'timeline', 'Sequence the work into credible phases.'],
      ['Team and Ways of Working', 'team', 'Establish delivery ownership and collaboration.'],
      ['Risks and Assumptions', 'narrative', 'Make dependencies visible and manageable.'],
      ['Commercial Considerations', 'commercials', 'Reserve the commercial decision for approval.'],
      ['Next Steps', 'next-steps', 'Create a clear path to alignment and action.'],
    ]),
  },
  {
    id: 'proposal-manufacturing-site-selection',
    fileName: 'DTMC_Sample_Proposal_02_Manufacturing_Site_Selection 1.pptx',
    assetPath: '/Asset/proposal-templates/DTMC_Sample_Proposal_02_Manufacturing_Site_Selection 1.pptx',
    name: 'Manufacturing Site Selection',
    description: 'A decision-oriented format for evaluating options, trade-offs, feasibility, and a recommended path.',
    audience: 'Investment committee and operations leadership',
    style: 'Evidence-led, comparative, and decision-focused',
    slideCount: 6,
    narrativeFlow: 'Decision context -> evaluation lens -> findings -> recommendation -> implementation',
    visualStyle: officeVisualStyle,
    slides: proposalSlides([
      ['Decision Overview', 'cover', 'State the decision and intended business impact.'],
      ['Business Context and Objectives', 'narrative', 'Anchor the decision in client priorities.'],
      ['Evaluation Criteria', 'narrative', 'Define how options will be assessed.'],
      ['Current Findings', 'narrative', 'Summarize evidence and constraints from intake.'],
      ['Options and Trade-offs', 'narrative', 'Present choices without inventing unsupported facts.'],
      ['Recommended Direction', 'narrative', 'Make the value case for the recommended path.'],
      ['Implementation Roadmap', 'timeline', 'Show how the decision becomes execution.'],
      ['Risks and Mitigations', 'narrative', 'Surface decision and delivery risk.'],
      ['Commercial Considerations', 'commercials', 'Reserve pricing and approval decisions.'],
      ['Next Steps', 'next-steps', 'Define the immediate decision and workshop sequence.'],
    ]),
  },
  {
    id: 'proposal-foundation-intranet',
    fileName: 'DTMC_Sample_Proposal_03_Foundation_Intranet 1.pptx',
    assetPath: '/Asset/proposal-templates/DTMC_Sample_Proposal_03_Foundation_Intranet 1.pptx',
    name: 'Foundation Intranet',
    description: 'A people-and-platform narrative for establishing an inclusive, scalable intranet foundation.',
    audience: 'Executive sponsors, communications, and technology teams',
    style: 'Human-centered, structured, and adoption-focused',
    slideCount: 6,
    narrativeFlow: 'People and purpose -> experience -> platform foundation -> adoption -> action',
    visualStyle: officeVisualStyle,
    slides: proposalSlides([
      ['A Better Employee Experience', 'cover', 'Open with the experience and value ambition.'],
      ['What We Heard', 'narrative', 'Reflect the client voice and discovery themes.'],
      ['Experience Principles', 'narrative', 'Turn needs into design principles.'],
      ['Proposed Intranet Foundation', 'narrative', 'Describe the experience, content, and platform model.'],
      ['Technology and Governance', 'architecture', 'Connect platform decisions to sustainable ownership.'],
      ['Adoption and Change Approach', 'narrative', 'Show how the solution becomes part of daily work.'],
      ['Phased Roadmap', 'timeline', 'Create a practical path from foundation to scale.'],
      ['Delivery Team', 'team', 'Clarify roles across business and technology.'],
      ['Commercial Considerations', 'commercials', 'Reserve pricing and approval decisions.'],
      ['Next Steps', 'next-steps', 'Move into alignment and planning.'],
    ]),
  },
  {
    id: 'proposal-responsible-ai-training',
    fileName: 'DTMC_Sample_Proposal_04_Responsible_AI_Training 1.pptx',
    assetPath: '/Asset/proposal-templates/DTMC_Sample_Proposal_04_Responsible_AI_Training 1.pptx',
    name: 'Responsible AI Training',
    description: 'A capability-building proposal that links responsible AI principles to measurable workforce readiness.',
    audience: 'Executive sponsors, risk leaders, and learning teams',
    style: 'Trust-led, capability-focused, and pragmatic',
    slideCount: 6,
    narrativeFlow: 'Why now -> readiness gap -> learning solution -> measurement -> commitment',
    visualStyle: officeVisualStyle,
    slides: proposalSlides([
      ['Responsible AI Readiness', 'cover', 'Frame the imperative and desired outcome.'],
      ['Why This Matters Now', 'narrative', 'Connect the initiative to client context and risk.'],
      ['Readiness and Capability Gaps', 'narrative', 'Describe observed needs without unsupported claims.'],
      ['Training Solution', 'narrative', 'Present the learning journey and experiences.'],
      ['Learning Architecture', 'architecture', 'Show how content, governance, and measurement connect.'],
      ['Measurement and Adoption', 'narrative', 'Define how capability and behavior will be evidenced.'],
      ['Delivery Roadmap', 'timeline', 'Sequence design, pilot, rollout, and reinforcement.'],
      ['Team and Governance', 'team', 'Establish accountability and subject matter support.'],
      ['Commercial Considerations', 'commercials', 'Reserve pricing and approval decisions.'],
      ['Next Steps', 'next-steps', 'Define the path to a focused kickoff.'],
    ]),
  },
];

export const getProposalTemplate = (templateId: string) =>
  PROPOSAL_TEMPLATES.find(template => template.id === templateId) || PROPOSAL_TEMPLATES[0];